---
- hosts: all
  collections:
    - devsec.hardening
  tasks:
    - name: Find local example file
      local_action: ansible.builtin.stat path='{{ example_name }}/docker-compose.server.yml'
      register: local_example_exists

    - name: Fail if local example file does not exists
      ansible.builtin.fail:
        msg: 'please provide existing example name'
      when: local_example_exists.stat.exists == false

    - name: Harden SSH
      import_role:
        name: ssh_hardening
      vars:
        ssh_permit_root_login: 'yes'
        ssh_max_auth_retries: 5

    - name: Update repositories cache
      apt:
        update_cache: 'yes'

    - name: Install Docker and Docker Compose
      import_role:
        name: nickjj.docker
      vars:
        docker__version: '20.10'
        docker__compose_version: '1.29'

    - name: Copy Docker Compose file
      ansible.builtin.copy:
        src: '{{ example_name }}/docker-compose.server.yml'
        dest: /tmp/docker-compose.server.yml
        mode: '0600'

    - name: Create and start Docker services
      community.docker.docker_compose:
        project_src: /tmp/
        files:
          - docker-compose.server.yml
      vars:
        ansible_python_interpreter: /usr/local/lib/docker/virtualenv/bin/python3.8
