---
- hosts: all
  collections:
    - devsec.hardening
  tasks:
    - name: Harden SSH
      import_role:
        name: ssh_hardening
      vars:
        ssh_permit_root_login: 'yes'
        ssh_max_auth_retries: 5