version: "2.4"
services:
  speed-test:
    image: networkstatic/iperf3
    expose:
      - 5201/tcp
      - 5201/udp
    command: "-s"
    healthcheck:
      test: iperf3 -c 127.0.0.1 -l1 -t1

  speed-test-tcp-tcp-proxy:
    image: ghcr.io/dlemel8/tunneler-server:${TAG:-main}
    environment:
      LOCAL_PORT: 45301
      REMOTE_PORT: 5201
      REMOTE_ADDRESS: speed-test
      TUNNELED_TYPE: tcp
    ports:
      - "45301:45301"
    command: "tcp"
    depends_on:
      speed-test:
        condition: service_healthy

  speed-test-udp-tcp-tunnel:
    image: ghcr.io/dlemel8/tunneler-server:${TAG:-main}
    environment:
      LOCAL_PORT: 45301
      REMOTE_PORT: 5201
      REMOTE_ADDRESS: speed-test
      TUNNELED_TYPE: udp
    ports:
      - "45302:45301"
    command: "tcp"
    depends_on:
      speed-test:
        condition: service_healthy

  speed-test-tcp-dns-tunnel:
    image: ghcr.io/dlemel8/tunneler-server:${TAG:-main}
    environment:
      LOCAL_PORT: 53535
      REMOTE_PORT: 5201
      REMOTE_ADDRESS: speed-test
      TUNNELED_TYPE: tcp
      READ_TIMEOUT_IN_MILLISECONDS: 100
      IDLE_CLIENT_TIMEOUT_IN_MILLISECONDS: 300000
    ports:
      - "53535:53535/udp"
    command: "dns"
    depends_on:
      speed-test:
        condition: service_healthy

  speed-test-udp-dns-tunnel:
    image: ghcr.io/dlemel8/tunneler-server:${TAG:-main}
    environment:
      LOCAL_PORT: 53535
      REMOTE_PORT: 5201
      REMOTE_ADDRESS: speed-test
      TUNNELED_TYPE: udp
      READ_TIMEOUT_IN_MILLISECONDS: 100
      IDLE_CLIENT_TIMEOUT_IN_MILLISECONDS: 300000
    ports:
      - "53536:53535/udp"
    command: "dns"
    depends_on:
      speed-test:
        condition: service_healthy
