version: "2.4"
services:
  speed-test:
    ports:
      - "45201:5201/tcp"
      - "45201:5201/udp"

  speed-test-tcp-tls-tunnel:
    volumes:
      - ../../pki/ca.crt:/ca_certificate
      - ../../pki/server.key:/server_key
      - ../../pki/server.crt:/server_certificate

  speed-test-udp-tls-tunnel:
    volumes:
      - ../../pki/ca.crt:/ca_certificate
      - ../../pki/server.key:/server_key
      - ../../pki/server.crt:/server_certificate
