name: Deploy an example server using Terraform and Ansible

on:
  workflow_dispatch:
    inputs:
      exampleName:
        description: 'Example Name'
        required: true
        default: 'speed_test'

env:
  TF_VAR_LINODE_API_TOKEN: ${{ secrets.LINODE_API_TOKEN }}
  TF_VAR_LINODE_PUBLIC_SSH_KEY: ${{ secrets.LINODE_PUBLIC_SSH_KEY }}
  TF_VAR_LINODE_ROOT_PASSWORD: ${{ secrets.LINODE_ROOT_PASSWORD }}

jobs:
  plan-server-infra:
    runs-on: ubuntu-latest
    outputs:
      plan-exitcode: ${{ steps.plan.outputs.exitcode }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Ansible inventory from cache
        uses: actions/cache@v2
        with:
          path: examples/${{ github.event.inputs.exampleName }}/ansible_inventory
          key: ansible-inventory-${{ github.run_id }}
          restore-keys: |
            ansible-inventory-

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.4
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      - name: Terraform plan
        id: plan
        run: |
          terraform init
          terraform plan -detailed-exitcode -out=/tmp/tfplan
        working-directory: examples/${{ github.event.inputs.exampleName }}
        continue-on-error: true

      - name: Verify Terraform plan
        if: ${{ steps.plan.outputs.exitcode == 1 }}
        run: exit ${{ steps.plan.outputs.exitcode }}

      - name: Cache plan
        uses: actions/cache@v2
        if: ${{ steps.plan.outputs.exitcode == 2 }}
        with:
          path: /tmp/tfplan
          key: tfplan-${{ github.run_id }}

  apply-server-infra:
    runs-on: ubuntu-latest
    environment: Example
    needs: [ plan-server-infra ]
    if: ${{ needs.plan-server-infra.outputs.plan-exitcode == 2 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get plan from cache
        uses: actions/cache@v2
        with:
          path: /tmp/tfplan
          key: tfplan-${{ github.run_id }}

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.4
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      - name: Terraform apply
        run: |
          terraform init
          terraform show /tmp/tfplan
          terraform apply /tmp/tfplan
        working-directory: examples/${{ github.event.inputs.exampleName }}

      - name: Cache Ansible inventory
        uses: actions/cache@v2
        with:
          path: examples/${{ github.event.inputs.exampleName }}/ansible_inventory
          key: ansible-inventory-${{ github.run_id }}

  configure-server:
    runs-on: ubuntu-latest
    needs: [ apply-server-infra ]
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Ansible inventory from cache
        uses: actions/cache@v2
        with:
          path: examples/${{ github.event.inputs.exampleName }}/ansible_inventory
          key: ansible-inventory-${{ github.run_id }}
          restore-keys: |
            ansible-inventory-

      - name: Load SSH key
        run: 'echo "$SSH_KEY" > /tmp/id_rsa && chmod 600 /tmp/id_rsa'
        shell: bash
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Extract pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('examples/${{ github.event.inputs.exampleName }}/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Ansible
        run: python3.9 -m pip install -r examples/${{ github.event.inputs.exampleName }}/requirements.txt

      - name: Install Ansible playbook dependencies
        run: ansible-galaxy collection install -r ansible_requirements.yml
        working-directory: examples/${{ github.event.inputs.exampleName }}

      - name: Run Ansible playbook
        run: ansible-playbook -i ansible_inventory --key-file /tmp/id_rsa ansible_playbook.yml
        working-directory: examples/${{ github.event.inputs.exampleName }}

