name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install examples runtime dependencies
        run: sudo apt-get install -y libpcap-dev
      - name: Install linters
        run: rustup component add clippy rustfmt
      - name: Clippy
        run: cargo clippy -- -D warnings
        working-directory: ./client
      - name: Rustfmt
        run: cargo fmt --all -- --check
        working-directory: ./client
      - name: Run tests
        run: cargo test --all-targets
        working-directory: ./client
