name: Build

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install linters
        run: rustup component add clippy rustfmt
      - name: Clippy
        run: cargo clippy --version && cargo clippy -- -D warnings
      - name: Rustfmt
        run: cargo fmt --version && cargo fmt --all -- --check
      - name: Run tests
        run: cargo test --all-targets
